#!/usr/bin/python3

import sys, re
delimeters = [';',',','/']
dicFile = open('dictionary','r')
dictionary = {}
for line in dicFile:
    word,data = line.split(delimeters[0])
    dictionary[word]=data
while True:
    line = sys.stdin.readline().strip().split()
    out = []
    for word in line:
        dicLine = dictionary[word]
        charsToCut  = re.findall(r"[0-9]*",dicLine)[0]
        core = word[:len(word) - int(charsToCut)]
        charsToAdd = re.findall(r"[^0-9][^,]*",dicLine)[0]
        out.append(core + charsToAdd)

    print(" ".join(out))
        


